### ISSUE TITLE
로그인 안 했을 경우 설명이 부족한 곳이 있어요

### ISSUE THREAD

**Issue by Jjungs7** [PoolC/SigAhri#13]
화면에 딱히 자신이 로그인 상태라는걸 표시해주는데가 없어서 유저 입장에선 왜 안 나오지? 왜 안되지? 하고 헷갈릴 수 있어요.
1. 투표를 클릭했을 때 로그인해달라는 표시
2. CommentInput은 보여주되 disabled 로 처리해서 placeholder로 로그인 후 이용 가능합니다 등의 문구 표시
3. 게시판 모두 표시. 하지만 클릭했을 경우 회원만 볼 수 있는 글입니다. 등의 문구 표시

**Comment by zych1751** [comment]
1. 로그인을 하지 않은 경우 투표 버튼 없앰
2. 로그인을 하지 않은 경우 댓글창 없앰
3. 현재 상태 그대로 권한 있는 게시판만 볼 수 있게 둠
