### ISSUE TITLE
code splitting

### ISSUE THREAD

**Issue by zych1751** [PoolC/SigAhri#30]
빌드할때 main.js 1MB 가까이 나오는데 권장 크기(244KB) 보다 크기 때문에 code splitting 할 필요가 있음.

**Comment by angdev** [comment]
제가 심심해서 webpack analyze 를 돌려봤는데 아래의 항목들이 개선할만한 점이라 생각됩니다.

<img width="1192" alt="2019-03-01 1 17 03" src="https://user-images.githubusercontent.com/1954350/53616074-5be90d80-3c24-11e9-8d56-2570495328b8.png">

1. `moment.js` 빌드를 최적화하거나 다른 라이브러리를 가져다가 쓴다.

쓸데없이 용량이 크고 기본적으로 로캐일 관련 스크립트가 많이 딸려와서 [이 글](https://medium.com/little-big-programming/spa-%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8-%EC%9A%A9%EB%9F%89-%EC%96%B4%EB%94%94%EA%B9%8C%EC%A7%80-%EC%A4%84%EC%9D%BC-%EC%88%98-%EC%9E%88%EC%9D%84%EA%B9%8C-69c7e05bb3b3#689d) 에 있는 것처럼 제거하거나 [date-fns](https://date-fns.org/) 같은 걸로 대체해볼 수 있지 않을까 합니다. (moment.js 는 모듈이 제대로 안 나뉘어 있어서 통짜로 빌드가 되는데 date-fns 를 쓰면 스크립트 사이즈 줄일 때 도움이 될 것 같습니다. moment.js 가 대단한 일을 하는 것이 아니라면 직접 작성한 코드로 대체를 해도 괜찮을 것 같아요)

<img width="392" alt="2019-03-01 1 18 33" src="https://user-images.githubusercontent.com/1954350/53616116-8935bb80-3c24-11e9-8362-9a826351e0d9.png">

제가 간단히 `ContextReplacementPlugin` 으로 moment.js ko locale 만 빼고 걷어내보니 `1115 KiB` -> `937 KiB` 로 일단 줄었습니다.

2. SimpleMDE 를 필요할 때 받아온다.

simplemde 자체는 50KiB 정도 되는 것 같은데 의존성으로 codemirror 를 가지고 있습니다. codemirror 만 대략 400KiB 이상의 크기를 차지합니다. 이는 게시글 작성할 때 정도 필요할 것으로 생각이 되는데, 별도로 스크립트로 분리하면 초기 로딩 속도 개선에 도움이 될 것 같아요.

3. static file gzip 압축을 한다.

<img width="295" alt="2019-03-01 1 19 34" src="https://user-images.githubusercontent.com/1954350/53616164-af5b5b80-3c24-11e9-82a6-ffc9e2382117.png">

서버에서 스크립트 내려줄 때 gzip 으로 압축해서 내려주면 현재 상태로도 342KB 정도로 압축이 되니 nginx 단에서 대응을 해주면 좋지 않을까 합니다.

**Comment by Jjungs7** [comment]
어떻게 해야할지 감이 안 와서 고민중이었는데 이렇게 자세하게 알려주셔서 금방 고칠 수 있을것같네요 감사합니다!! 🙌

**Comment by Jjungs7** [comment]
- 1차 Optimization
  - momentjs 제거
  - SimpleMDE lazy loading
  - poolc.org gzip 압축
위 사항 적용하였음. 추가 최적화 사항으로 
1. bundle.js 파일들을 gzip 으로 압축
2. min.css 파일들 lazy loading

기타사항은 [Google PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fpoolc.org%2F) 참고

**Comment by Jjungs7** [comment]
bundle.js gzip 으로 압축하였음 (v.1.2.3

**Comment by Jjungs7** [comment]
code splitting 에 관하여 어느정도 진행되었으므로 추가적으로 최적화할만한 사항들은 새로운 이슈에서 다루겠음
