### ISSUE TITLE
파일 업로드에 확장자로 제약이 걸림

### ISSUE THREAD

**Issue by HelloDHLyn** [PoolC/SigAhri#52]
실제로는 확장자 제약이 없는데 업로드를 시도하면 아래 스크린샷처럼 막혀요

![D6D66C2E-E608-4F98-9C06-80EB1040AFEA](https://user-images.githubusercontent.com/8597749/55213950-635a0180-5238-11e9-906a-2652995ef7bb.png)

**Comment by HelloDHLyn** [comment]
근데 jpg 파일 올린건데 왜 막혔지;;

**Comment by zych1751** [comment]
https://github.com/PoolC/SigAhri/pull/53
수정하였습니당
